name: crypto_rtq
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Flutter Essentials
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1

  # Routing
  go_router: ^14.8.1

  # Networking
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2

  # Utilities
  collection: ^1.19.1
  intl: ^0.20.2

  # UI
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

flutter:
  uses-material-design: true
