name: crypto_rtq
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2
  equatable: ^2.0.7
  intl: ^0.20.2
  shimmer: ^3.0.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

